spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 5
        keep-alive: 60
  profiles:
    active: dev
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1797213901@qq.com
    password: hipjxdrfyrtzejde
    port: 587

qiniu:
  accessKey: 1xyIa5WiiaGovp-i7-KpMOW11ZkPRrxEw0Ruhyyd
  secretKey: te9hRcZCcxGkKWHvXu9g4PXumtgOM8mHhnJala7A
  bucket: youfa-chen


